### ISSUE TITLE
Shift+F10 does not work on files/folders in mobile mode

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder#151] opened 2015-05-27 14:26 UTC
Focus file or a folder, press Shift+F10.

Expected result: context menu is opened.
Current result: nothing happens.

Similar to #150

**Comment by jodator** [comment] 2015-05-28 07:02
Duplicate of #150. If this don't work the reason is the same.

**Closed by jodator** 2015-05-28 07:02 UTC
Labels: Bug, Duplicate, Keyboard
