### ISSUE TITLE
CKFinder3 gives out "folder not found" error when multiple instances are loaded in the same browser in different tabs

### ISSUE THREAD

**Issue by millzee01** [ckfinder/ckfinder#344] opened 2018-01-26 09:45 UTC
Are you reporting a feature request or a bug?
BUG

Launch 1st ckfinder as CKFinder.start( { id: 'A') } with a resource named "files" pointing to a folder called "Images" in browser tab1

Create a new folder in "files" called TESTA and open it

Launch 2nd ckfinder as CKFinder.start( { id: 'B') } with a resource named "files" pointing to a folder called "Files" in browser tab2 (so both ckfinders are loaded with the same resource names but pointing to different folders)

Create a new folder in "Files" called TESTB and open in

Now go back to Tab1 and click "files" folder then click "TESTA" folder

Now go to Tab2 and click "Files" folder, then open "TESTB" folder

Expected result
As we are using different id's we would expect both to operate independently and work between folders without errors

Actual result
The following CKFinder error appears in 1st CKFinder instance (A) indicating that the instance feature of CKFinder does not work when using multiple CKfinder pages

error:/Images/TESTB/
Fatal error: Uncaught CKSource\CKFinder\Exception\FolderNotFoundException: Folder not found

However if we open each CKFinder on their own no error is shown and app operates normally.

Other details
Any (Google, FireFox, IE and Safari)
OS: Windows
CKFinder version: 3
No plugins installed.

**Comment by jswiderski** [comment] 2018-01-26 16:06
Please tell us exactly what configuration have you used because from what we have tried everything worked as expected. We did the below:

1. We have created two instances on two separate HTML pages with below configuration:

**Instance A**
```
CKFinder.widget( 'ckfinder-widget', {
		id : 'bb',
		pass : 'id',
		width: '100%',
		height: 700,
		onInit: function( finder ) {			
		}
	} );	

```
**Instance B**
```
CKFinder.widget( 'ckfinder-widget', {
		id : 'bb',
		pass : 'id',
		width: '100%',
		height: 700,
		onInit: function( finder ) {			
		}
	} );	

```

2. Inside `config.php` we have set up one `default` backend which points to `userfiles` folder inside the CKFinder folder and set the Files resource type as below:
```
$config['resourceTypes'][] = array(
    'name'              => 'Files', 
    'directory'         => strcmp($_GET['id'], 'aa') == 0 ? 'images' : 'files',
    'maxSize'           => 0,
    'allowedExtensions' => 'css,js,7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip,ogv,webm',
    'deniedExtensions'  => '',
    'backend'           => 'default'
);
```
3. Inside the `ckfinder/userfiles` folder we had two subfolders - `images` and `files`.
4. Next we have followed your instructions and created two different folders. We clicked on them uploaded files to both but nothing unexpected happened.

Please tell us where the difference is. What should we do differently to reproduce this problem?

**Comment by millzee01** [comment] 2018-01-29 07:45
Hi, i believe the only difference is the way we start ckfinder.
our init page:

<?php 
	$_SESSION["libraryid"] = 1001; //generted unique id 
?>

CKFinder.start( { id: '<?php echo $_SESSION["libraryid"];?>' , pass: 'id' ,
	onInit: function(finder) { 
		console.log("id=" + id);
	}
} );

**Comment by jswiderski** [comment] 2018-01-29 10:39
Could you try our basic example then and see if it is working for you? If it does work, this will mean a problem in how CKFinder is implemented on your side.

If you need any more details or files from our basic setup, please let us know. 

Please also use standalone CKFinder, not integrated into your application in order to exclude it influence on the problem.

**Comment by millzee01** [comment] 2018-01-29 12:40
Ok, i tested using the widget method and the same issue occurs when flicking between tabs and negotiating folders:

Fatal error: Uncaught CKSource\CKFinder\Exception\FolderNotFoundException: Folder not found

Our server is a windows 2012 server btw.

`
<body id="ckfinder-widget">
	CKFinder.widget( 'ckfinder-widget', {
		id : '<?php echo $_SESSION["lib_libraryid"];?>',
		pass: '<?php echo $_SESSION["lib_libraryid"];?>',
		onInit: function(finder) { 
			console.log("id=" + id); 
		} 
	} );
</body>
`
if we run 1 instance then it works flawless.
however  2 instances causes issues as we described.

here's our config:

config.php
$baseUrl = '/boards'; //points to D:/personal/data 
$baseDir = 'D:/personal/data';
$config['unixpath']="/".$_SESSION['lib_unixpath']."/"; // user folder (/1000/x   x = userid])

//personal library backend
$config['backends'][] = array(
    'name'         => 'default',
    'adapter'      => 'local',
    'baseUrl'      => $baseUrl.$config['unixpath'],
    'root'         => $baseDir.$config['unixpath'],
    'chmodFiles'   => 0777,
    'chmodFolders' => 0755,
    'filesystemEncoding' => 'UTF-8'
);

//***********************************************************************************
// My Documents
//***********************************************************************************
$config['resourceTypes'][] = array(
    'name'              => 'files',
    'label'              => "My Documents",
    'directory'         => 'gallery/files/',
    'maxSize'           => "2000K",
    'allowedExtensions' => 'pdf',
    'deniedExtensions'  => 'jpg, jpeg,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip',
    'backend'           => 'default'
);

//***********************************************************************************
// My Images resource
//***********************************************************************************
$config['resourceTypes'][] = array(
    'name'              => 'images',
    'label'              => "My Images",
    'directory'         => 'gallery/files/',
    'maxSize'           => "2000K",
    'allowedExtensions' => 'jpg,jpeg',
    'deniedExtensions'  => 'aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip',
    'backend'           => 'default'
);

**Comment by jswiderski** [comment] 2018-01-31 15:08
@millzee01 I have tried couple of times but could not reproduce the problem. Could you attach zip file (or a link to zip file on e.g. dropbox ) with your test sandbox which is causing problems for you. Once we put on our server that default CKFinder application prepared by you, we should be able to tell more about the problem. 

NOTE: Just please make sure this is the default sample which doesn’t require any custom code of your application like access to Data Base etc.

**Comment by zaak** [comment] 2018-06-01 15:01
This issue has been resolved through [technical support channel](https://ckeditor.com/contact/). Closing.

**Closed by zaak** 2018-06-01 15:01 UTC
