### ISSUE TITLE
Language file is missing or Broken

### ISSUE THREAD

**Issue by steg1986** [ckfinder/ckfinder#169] opened 2015-06-01 23:39 UTC
Could not start CKFinder: Language file is missing or broken.  bug found on new installation of preview

![image](https://cloud.githubusercontent.com/assets/8006539/7925671/bbca7104-08bf-11e5-817a-09aaa214d743.png)

screenie attached

**Comment by jodator** [comment] 2015-06-02 08:19
Hi @steg1986, thanks for reporting, but I cannot reproduce this issue so could you provide some more information about that issue?
I can see that you use Chrome on Windows 8/8.1, but could you also check:
- what server do you use for running CKFinder installation?
- what's language setting of your browser?
- does it happen only on popups sample or on others too?

Also if you could provide any errors from console (from popup window) that might be helpful also.

A default language file should be located at (reading URL of CKFinder installation from screenshot):
`http://localhost:22351/ckfinder/lang/en.json` (you might need to change port if it is dynamic configuration).

**Comment by wwalc** [comment] 2015-06-02 08:23
Any chance that you tried to create your own localization based on `en.js` file which you renamed?

**Comment by steg1986** [comment] 2015-06-02 09:34
Hi Guys, 

Thanks for the replies, pointed me in the right direction (going to the .json file returned and error).

I am running the system using IIS Express (PHP Tools for visual studio) the .json Mime type was not installed on my server.

adding the .json mime type to IIS Express configuration solved this problem.

Regards,
Stephen

**Comment by jodator** [comment] 2015-06-02 10:00
Good to know that IIS Express has that default configuration.
As I get it right, without adding JSON Mime Type, the IIS Express returns  403 Error, not the file itself, as found here: [link](http://stackoverflow.com/questions/19516829/allow-loading-of-json-files-in-visual-studio-express-2013-for-web).

We might think in future how to overcome such configurations, like serving a plain text file or as a .js file (a bit hackish) but that will require checking for other server solutions that might mess with UTF-8 encoding (namely Java servers).

I'm closing this for now, as case is solved, keeping this post as a reminder for later.
We also should add a note for IIS Express configuration to docs.

**Closed by jodator** 2015-06-02 10:00 UTC
