### ISSUE TITLE
Bottom or top folder sometimes is not displayed properly

### ISSUE THREAD

**Issue by zaak** [ckfinder/ckfinder#139] opened 2015-05-27 12:09 UTC
This looks like a random bug, I couldn't find any pattern when it happens. In case if folders tree overflows the tree pane, top or bottom folders are not displayed and you cannot scroll to them.

On both screens below there's a folder that you cannot scroll to.

Top:
![screen_shot_2015-05-27_at_13 50 05](https://cloud.githubusercontent.com/assets/803299/7835713/45ee21ee-047b-11e5-8f0e-5da9a094f2f1.png)

Bottom:
![bottom](https://cloud.githubusercontent.com/assets/803299/7835430/30b9ebfc-0479-11e5-8951-c75ac9c68eb8.png)

**Comment by wwalc** [comment] 2015-10-21 11:12
Most probably fixed in 3.0.0. Could not reproduce it for a long time.

**Closed by wwalc** 2015-10-21 11:12 UTC
